services:
  api-clt:
    build: .
    container_name: clt_prueba_api
    ports:
      - "5165:5165"
    volumes:
      - ./data:/app/data # Carpeta para persistir la DB SQLite
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
